# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Build the repository

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
        
    #- name: Install Google Chrome # Using shell script to install Google Chrome
    #  run: |
    #   chmod +x ./scripts/InstallChrome.sh
    #    ./scripts/InstallChrome.sh
    - name: Build & Run tests with Maven
      #run: mvn clean test -DsuiteXmlFile=testNGsuite/djiBangalore.xml
      run: mvn clean install -DskipTests=true
